# Generated by Django 5.2.6 on 2025-09-25 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_cadastro_completo_customuser_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='endereco',
        ),
        migrations.AddField(
            model_name='customuser',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_emissao_rg',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão do RG'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='descricao_lider',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição de Liderança'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_alternativo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Alternativo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereco_simples',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço Simples'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='formacao_academica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='habilidade_artistica',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidade Artística'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='habilidade_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidade Extra'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='habilidade_manual',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidade Manual'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instrumento',
            field=models.TextField(blank=True, null=True, verbose_name='Instrumento Musical'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado pelo Gestor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ja_foi_paioleiro',
            field=models.BooleanField(default=False, verbose_name='Já Foi Paioleiro'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ja_frequentou_acampamento',
            field=models.BooleanField(default=False, verbose_name='Já Frequentou Acampamento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ja_trabalhou_como_monitor',
            field=models.BooleanField(default=False, verbose_name='Já Trabalhou como Monitor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pis',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='PIS'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pratica_esporte',
            field=models.TextField(blank=True, null=True, verbose_name='Pratica Esporte'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qual_restricao',
            field=models.TextField(blank=True, null=True, verbose_name='Qual Restrição'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='restricao_alimentar',
            field=models.BooleanField(default=False, verbose_name='Possui Restrição Alimentar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site Pessoal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trabalha_atualmente',
            field=models.BooleanField(default=False, verbose_name='Trabalha Atualmente'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereco_completo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.endereco', verbose_name='Endereço Completo'),
        ),
    ]
