# Generated by Django 5.2.6 on 2025-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categoria_ajuda_custo',
            field=models.CharField(blank=True, choices=[('ajuda_1', 'Ajuda de Custo 1'), ('ajuda_2', 'Ajuda de Custo 2'), ('ajuda_3', 'Ajuda de Custo 3')], max_length=20, null=True, verbose_name='Categoria Ajuda de Custo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='categoria_funcao',
            field=models.CharField(blank=True, choices=[('conselheiro_senior', 'Conselheiro Senior'), ('conselheiro', 'Conselheiro'), ('monitor', 'Monitor'), ('monitor_junior', 'Monitor Junior'), ('estagiario', 'Estagiário'), ('day_camp', 'Day Camp'), ('enfermeira', 'Enfermeira'), ('enfermeira_estagiaria', 'Enfermeira Estagiária'), ('fotografo_1', 'Fotógrafo 1'), ('fotografo_2', 'Fotógrafo 2')], max_length=30, null=True, verbose_name='Categoria da Função'),
        ),
    ]
