# Generated by Django 5.1.7 on 2025-03-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('ferias', 'Férias'), ('familia', 'Familia'), ('dayuse', 'Day Use'), ('evento', 'Evento Especial')], max_length=20)),
            ],
        ),
    ]
