# Generated by Django 5.1.7 on 2025-03-25 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporadas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interessado', 'Interessado'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('confirmado', 'Confirmado')], default='interessado', max_length=20)),
                ('data_interesse', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(limit_choices_to={'user_type': 'monitor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporadas.temporada')),
            ],
            options={
                'unique_together': {('monitor', 'temporada')},
            },
        ),
    ]
