# Generated by Django 5.1.7 on 2025-03-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporadas', '0002_interessetemporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
