# Generated by Django 5.2.6 on 2025-10-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporadas', '0003_temporada_email_enviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='nome',
        ),
        migrations.AddField(
            model_name='temporada',
            name='horario_chegada_equipe',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Chegada Equipe'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='horario_saida_equipe',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Saída Equipe'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='numero_diarias',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Ex: 3.5 para três dias e meio', max_digits=4, verbose_name='Número de Diárias'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='tem_ajuda_custo',
            field=models.BooleanField(default=False, verbose_name='Tem Ajuda de Custo'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='tem_desembarque',
            field=models.BooleanField(default=False, verbose_name='Tem Desembarque'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='tem_embarque',
            field=models.BooleanField(default=False, verbose_name='Tem Embarque'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='data_fim',
            field=models.DateField(verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='tipo',
            field=models.CharField(choices=[('escola', 'Escola'), ('dayuse', 'Day Use'), ('familia', 'Família'), ('ferias', 'Férias'), ('evento', 'Evento Especial')], max_length=20, verbose_name='Tipo'),
        ),
    ]
