# Generated by Django 5.1.7 on 2025-10-21 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporadas', '0004_extend_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='monitores',
            field=models.ManyToManyField(related_name='temporadas', through='temporadas.TemporadaEquipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
